<?xml version='1.0' encoding='UTF-8'?><!-- Published by JAX-WS RI (http://jax-ws.java.net). RI's version is Metro/2.4.3.payara-p3 (2.4.3.payara-maintenance-a5c1c68; 2019-06-17T14:04:38+0200) JAXWS-RI/2.3.2.payara-p2 JAXWS-API/2.3.2 JAXB-RI/2.3.2 JAXB-API/2.3.2 git-revision#unknown. --><definitions xmlns:tns="http://javeriana.usnotificaciones/service/v1.0.0/notificaciones" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://javeriana.usnotificaciones/service/v1.0.0/notificaciones" name="USNotificacionesService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://javeriana.usnotificaciones/service/v1.0.0/notificaciones" schemaLocation="http://localhost:8080/us-notificaciones/USNotificacionesService?xsd=1"/>
    </xsd:schema>
  </types>
  <message name="enviarNotificacionRequest">
    <part name="cabecera" element="tns:cabecera"/>
    <part name="parameters" element="tns:enviarNotificacionRequest"/>
  </message>
  <message name="enviarNotificacionResponse">
    <part name="result" element="tns:enviarNotificacionResponse"/>
  </message>
  
  <portType name="USNotificaciones_PortType">
    <operation name="enviarNotificacion">
      <input message="tns:enviarNotificacionRequest"/>
      <output message="tns:enviarNotificacionResponse"/>
    </operation>    
  </portType>
  <binding name="USNotificacionesServicePortBinding" type="tns:USNotificaciones_PortType">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="enviarNotificacion">
      <soap:operation soapAction="enviarNotificacion"/>
      <input>
        <soap:body use="literal" parts="parameters"/>
        <soap:header message="tns:enviarNotificacionRequest" part="cabecera" use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>   
  </binding>
  <service name="USNotificacionesService">
    <port name="USNotificacionesPort" binding="tns:USNotificacionesServicePortBinding">
      <soap:address location="http://localhost:8080/us-notificaciones/USNotificacionesService"/>
    </port>
  </service>
</definitions>